// Root Stylelint config (brief §5.3, ADR 0009, 0024). Every value that has a token is a token: colours, lengths,
// durations and easings may not appear raw. tools/lint-rules proves each rule with a failing fixture.
import { join } from 'node:path';
import {
  applicationRules,
  keywords,
  motionShorthands,
  strictValues,
} from './tools/lint-rules/src/stylelint/application-rules.ts';
import { plugins as avelune } from './tools/lint-rules/src/stylelint/index.ts';

const tokensCss = join(import.meta.dirname, 'packages', 'tokens', 'dist', 'tokens.css');

/** The cascade layers, lowest first; styles.css declares them in this order (brief §6.1, ADR 0004, 0030). */
const layerOrder = ['reset', 'tokens', 'base', 'components', 'patterns', 'utilities', 'app'];

export default {
  extends: ['stylelint-config-standard'],
  plugins: [
    'stylelint-declaration-strict-value',
    'stylelint-value-no-unknown-custom-properties',
    'stylelint-plugin-logical-css',
    ...avelune,
  ],
  defaultSeverity: 'error',
  reportDescriptionlessDisables: true,
  reportInvalidScopeDisables: true,
  reportNeedlessDisables: true,
  ignoreFiles: [
    '**/dist/**',
    '**/node_modules/**',
    '**/coverage/**',
    // Deliberate violations: tools/lint-rules asserts that each is rejected (brief §5).
    'tools/*/fixtures/**',
    // Generated by tools/fonts and verified by fonts:check against a fresh build (ADR 0018).
    'packages/ui/styles/fonts/fonts.css',
  ],
  rules: {
    // Every CSS file's rules, an application's too: @avelune/stylelint-config applies the same (ADR 0104).
    ...applicationRules(tokensCss),
    // A custom property is a token of tokens.css or declared in the same file, as a component's private ones are.
    'csstools/value-no-unknown-custom-properties': [true, { importFrom: [tokensCss] }],
    // A host with variant, size and state attributes plus one pseudo-class: :host([a][b]:hover) is 0,4,0.
    'selector-max-specificity': '0,4,0',
  },
  overrides: [
    {
      // The one home of @keyframes: the motion catalog (brief §6.3, ADR 0005). Its loops (skeleton, spinner) run at
      // a constant rate, `linear`, the one easing that is no token; tools/invariants accepts it only on a loop (ADR 0031).
      files: ['packages/ui/styles/motion.css'],
      rules: {
        'at-rule-disallowed-list': null,
        'scale-unlimited/declaration-strict-value': strictValues([...keywords, 'linear']),
      },
    },
    {
      // An entry point's styles are components; a pattern's (its entry.json says so) are patterns, which place the
      // kit's components in their templates and never restyle them (ADR 0091).
      files: ['packages/ui/*/**/*.css'],
      rules: {
        'avelune/component-layer': ['components', { entryLayers: { patterns: 'patterns' } }],
        'avelune/pattern-layout-only': true,
      },
    },
    {
      // The global stylesheets wrap their rules in the layers below and above the components (ADR 0030).
      files: ['packages/ui/styles/**/*.css'],
      rules: { 'avelune/component-layer': [['reset', 'base', 'utilities']] },
    },
    {
      // The entry point declares the layer order, then imports the tokens, the fonts and the layered files.
      files: ['packages/ui/styles/styles.css'],
      rules: { 'avelune/component-layer': null, 'avelune/layer-order': [layerOrder] },
    },
    {
      // The showcase is styled as an application: it declares no --ave-* property and reads tokens only, as
      // @avelune/stylelint-config requires (ADR 0089, 0104).
      files: ['apps/showcase/**/*.css'],
      rules: {
        'avelune/no-token-declarations': true,
        'avelune/known-tokens': [true, { tokens: tokensCss }],
      },
    },
    {
      // The one focus-ring rule (brief §6.1).
      files: ['packages/ui/styles/focus.css'],
      rules: { 'property-disallowed-list': motionShorthands },
    },
  ],
};
