// Generated by packages/icons/scripts/generate.ts from lucide-static 1.47.0 (ISC, LICENSE-lucide.txt) and
// scripts/icons.config.ts. Do not edit: change the config and run `pnpm nx run icons:generate --update` (ADR 0033).

/** One element of an icon, on Lucide's 24 × 24 grid, stroked with the current colour. */
export type IconElement =
  | { readonly tag: 'path'; readonly d: string }
  | { readonly tag: 'circle'; readonly cx: string; readonly cy: string; readonly r: string }
  | { readonly tag: 'line'; readonly x1: string; readonly x2: string; readonly y1: string; readonly y2: string }
  | {
      readonly tag: 'rect';
      readonly height: string;
      readonly width: string;
      readonly x: string;
      readonly y: string;
      readonly rx?: string;
      readonly ry?: string;
    };

/** The kit's icons: outlines on a 24 × 24 grid (ADR 0020). */
export const icons = {
  'arrow-down': [
    { tag: 'path', d: 'M12 5v14' },
    { tag: 'path', d: 'm19 12-7 7-7-7' },
  ],
  'arrow-left': [
    { tag: 'path', d: 'm12 19-7-7 7-7' },
    { tag: 'path', d: 'M19 12H5' },
  ],
  'arrow-right': [
    { tag: 'path', d: 'M5 12h14' },
    { tag: 'path', d: 'm12 5 7 7-7 7' },
  ],
  'arrow-up': [
    { tag: 'path', d: 'm5 12 7-7 7 7' },
    { tag: 'path', d: 'M12 19V5' },
  ],
  bell: [
    { tag: 'path', d: 'M10.268 21a2 2 0 0 0 3.464 0' },
    {
      tag: 'path',
      d: 'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
    },
  ],
  calendar: [
    { tag: 'path', d: 'M8 2v3' },
    { tag: 'path', d: 'M16 2v3' },
    { tag: 'rect', height: '18', rx: '2', width: '18', x: '3', y: '3' },
    { tag: 'path', d: 'M3 9h18' },
  ],
  check: [{ tag: 'path', d: 'M20 6 9 17l-5-5' }],
  'chevron-down': [{ tag: 'path', d: 'm6 9 6 6 6-6' }],
  'chevron-left': [{ tag: 'path', d: 'm15 18-6-6 6-6' }],
  'chevron-right': [{ tag: 'path', d: 'm9 18 6-6-6-6' }],
  'chevron-up': [{ tag: 'path', d: 'm18 15-6-6-6 6' }],
  'chevrons-left': [
    { tag: 'path', d: 'm11 17-5-5 5-5' },
    { tag: 'path', d: 'm18 17-5-5 5-5' },
  ],
  'chevrons-right': [
    { tag: 'path', d: 'm6 17 5-5-5-5' },
    { tag: 'path', d: 'm13 17 5-5-5-5' },
  ],
  'circle-alert': [
    { tag: 'circle', cx: '12', cy: '12', r: '10' },
    { tag: 'line', x1: '12', x2: '12', y1: '8', y2: '12' },
    { tag: 'line', x1: '12', x2: '12.01', y1: '16', y2: '16' },
  ],
  'circle-check': [
    { tag: 'circle', cx: '12', cy: '12', r: '10' },
    { tag: 'path', d: 'm16 9-5.5 5.5L8 12' },
  ],
  'circle-x': [
    { tag: 'circle', cx: '12', cy: '12', r: '10' },
    { tag: 'path', d: 'm15 9-6 6' },
    { tag: 'path', d: 'm9 9 6 6' },
  ],
  clock: [
    { tag: 'circle', cx: '12', cy: '12', r: '10' },
    { tag: 'path', d: 'M12 6v6l4 2' },
  ],
  copy: [
    { tag: 'rect', height: '14', rx: '2', ry: '2', width: '14', x: '8', y: '8' },
    { tag: 'path', d: 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2' },
  ],
  download: [
    { tag: 'path', d: 'M12 15V3' },
    { tag: 'path', d: 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4' },
    { tag: 'path', d: 'm7 10 5 5 5-5' },
  ],
  ellipsis: [
    { tag: 'circle', cx: '12', cy: '12', r: '1' },
    { tag: 'circle', cx: '19', cy: '12', r: '1' },
    { tag: 'circle', cx: '5', cy: '12', r: '1' },
  ],
  'ellipsis-vertical': [
    { tag: 'circle', cx: '12', cy: '12', r: '1' },
    { tag: 'circle', cx: '12', cy: '5', r: '1' },
    { tag: 'circle', cx: '12', cy: '19', r: '1' },
  ],
  'external-link': [
    { tag: 'path', d: 'M15 3h6v6' },
    { tag: 'path', d: 'M10 14 21 3' },
    { tag: 'path', d: 'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6' },
  ],
  eye: [
    {
      tag: 'path',
      d: 'M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0',
    },
    { tag: 'circle', cx: '12', cy: '12', r: '3' },
  ],
  'eye-off': [
    {
      tag: 'path',
      d: 'M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49',
    },
    { tag: 'path', d: 'M14.084 14.158a3 3 0 0 1-4.242-4.242' },
    { tag: 'path', d: 'M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143' },
    { tag: 'path', d: 'm2 2 20 20' },
  ],
  file: [
    {
      tag: 'path',
      d: 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
    },
    { tag: 'path', d: 'M14 2v5a1 1 0 0 0 1 1h5' },
  ],
  'file-text': [
    {
      tag: 'path',
      d: 'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
    },
    { tag: 'path', d: 'M14 2v5a1 1 0 0 0 1 1h5' },
    { tag: 'path', d: 'M10 9H8' },
    { tag: 'path', d: 'M16 13H8' },
    { tag: 'path', d: 'M16 17H8' },
  ],
  folder: [
    {
      tag: 'path',
      d: 'M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z',
    },
  ],
  funnel: [
    {
      tag: 'path',
      d: 'M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z',
    },
  ],
  'grip-vertical': [
    { tag: 'circle', cx: '9', cy: '12', r: '1' },
    { tag: 'circle', cx: '9', cy: '5', r: '1' },
    { tag: 'circle', cx: '9', cy: '19', r: '1' },
    { tag: 'circle', cx: '15', cy: '12', r: '1' },
    { tag: 'circle', cx: '15', cy: '5', r: '1' },
    { tag: 'circle', cx: '15', cy: '19', r: '1' },
  ],
  house: [
    { tag: 'path', d: 'M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8' },
    {
      tag: 'path',
      d: 'M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z',
    },
  ],
  info: [
    { tag: 'circle', cx: '12', cy: '12', r: '10' },
    { tag: 'path', d: 'M12 16v-4' },
    { tag: 'path', d: 'M12 8h.01' },
  ],
  lock: [
    { tag: 'rect', height: '11', rx: '2', ry: '2', width: '18', x: '3', y: '11' },
    { tag: 'path', d: 'M7 11V7a5 5 0 0 1 10 0v4' },
  ],
  'log-out': [
    { tag: 'path', d: 'm16 17 5-5-5-5' },
    { tag: 'path', d: 'M21 12H9' },
    { tag: 'path', d: 'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4' },
  ],
  mail: [
    { tag: 'path', d: 'm22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7' },
    { tag: 'rect', height: '16', rx: '2', width: '20', x: '2', y: '4' },
  ],
  menu: [
    { tag: 'path', d: 'M4 5h16' },
    { tag: 'path', d: 'M4 12h16' },
    { tag: 'path', d: 'M4 19h16' },
  ],
  minus: [{ tag: 'path', d: 'M5 12h14' }],
  monitor: [
    { tag: 'rect', height: '14', rx: '2', width: '20', x: '2', y: '3' },
    { tag: 'line', x1: '8', x2: '16', y1: '21', y2: '21' },
    { tag: 'line', x1: '12', x2: '12', y1: '17', y2: '21' },
  ],
  moon: [
    {
      tag: 'path',
      d: 'M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401',
    },
  ],
  'panel-left': [
    { tag: 'rect', height: '18', rx: '2', width: '18', x: '3', y: '3' },
    { tag: 'path', d: 'M9 3v18' },
  ],
  paperclip: [
    {
      tag: 'path',
      d: 'm16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551',
    },
  ],
  pencil: [
    {
      tag: 'path',
      d: 'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
    },
    { tag: 'path', d: 'm15 5 4 4' },
  ],
  phone: [
    {
      tag: 'path',
      d: 'M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384',
    },
  ],
  plus: [
    { tag: 'path', d: 'M5 12h14' },
    { tag: 'path', d: 'M12 5v14' },
  ],
  'refresh-cw': [
    { tag: 'path', d: 'M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8' },
    { tag: 'path', d: 'M21 3v5h-5' },
    { tag: 'path', d: 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16' },
    { tag: 'path', d: 'M8 16H3v5' },
  ],
  search: [
    { tag: 'path', d: 'm21 21-4.34-4.34' },
    { tag: 'circle', cx: '11', cy: '11', r: '8' },
  ],
  settings: [
    {
      tag: 'path',
      d: 'M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915',
    },
    { tag: 'circle', cx: '12', cy: '12', r: '3' },
  ],
  sun: [
    { tag: 'circle', cx: '12', cy: '12', r: '4' },
    { tag: 'path', d: 'M12 2v2' },
    { tag: 'path', d: 'M12 20v2' },
    { tag: 'path', d: 'm4.93 4.93 1.41 1.41' },
    { tag: 'path', d: 'm17.66 17.66 1.41 1.41' },
    { tag: 'path', d: 'M2 12h2' },
    { tag: 'path', d: 'M20 12h2' },
    { tag: 'path', d: 'm6.34 17.66-1.41 1.41' },
    { tag: 'path', d: 'm19.07 4.93-1.41 1.41' },
  ],
  trash: [
    { tag: 'path', d: 'M10 11v6' },
    { tag: 'path', d: 'M14 11v6' },
    { tag: 'path', d: 'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6' },
    { tag: 'path', d: 'M3 6h18' },
    { tag: 'path', d: 'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2' },
  ],
  'triangle-alert': [
    { tag: 'path', d: 'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3' },
    { tag: 'path', d: 'M12 9v4' },
    { tag: 'path', d: 'M12 17h.01' },
  ],
  upload: [
    { tag: 'path', d: 'M12 3v12' },
    { tag: 'path', d: 'm17 8-5-5-5 5' },
    { tag: 'path', d: 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4' },
  ],
  user: [
    { tag: 'path', d: 'M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2' },
    { tag: 'circle', cx: '12', cy: '7', r: '4' },
  ],
  x: [
    { tag: 'path', d: 'M18 6 6 18' },
    { tag: 'path', d: 'm6 6 12 12' },
  ],
} as const satisfies Readonly<Record<string, readonly IconElement[]>>;

/** The name of an icon in the kit. */
export type IconName = keyof typeof icons;

/** Every icon name, in order. */
export const iconNames = [
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'bell',
  'calendar',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-left',
  'chevrons-right',
  'circle-alert',
  'circle-check',
  'circle-x',
  'clock',
  'copy',
  'download',
  'ellipsis',
  'ellipsis-vertical',
  'external-link',
  'eye',
  'eye-off',
  'file',
  'file-text',
  'folder',
  'funnel',
  'grip-vertical',
  'house',
  'info',
  'lock',
  'log-out',
  'mail',
  'menu',
  'minus',
  'monitor',
  'moon',
  'panel-left',
  'paperclip',
  'pencil',
  'phone',
  'plus',
  'refresh-cw',
  'search',
  'settings',
  'sun',
  'trash',
  'triangle-alert',
  'upload',
  'user',
  'x',
] as const satisfies readonly IconName[];
