// Token build (ADR 0003, 0017): resolves the DTCG sources with Style Dictionary and writes
//   dist/tokens.css   semantic and component tokens as --ave-* custom properties, per theme, density and motion
//   dist/tokens.ts    typed values, CSS variable names and the TokenName union
// Primitives are resolved but never emitted.
//
//   node scripts/build.ts [--out <dir>]
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import StyleDictionary from 'style-dictionary';
import { modes, readManifest, type Mode } from './sources.ts';
import { convertToken, isTokenType, type ConvertedToken, type TokenType } from './token-values.ts';

const packageRoot = join(import.meta.dirname, '..');
const args = process.argv.slice(2);
const outIndex = args.indexOf('--out');
const outDir = resolve(outIndex === -1 ? join(packageRoot, 'dist') : (args[outIndex + 1] ?? ''));

/** Where each override lands in the CSS, and its key in tokens.ts. */
const placements: Readonly<Record<string, { readonly key: ModeKey; readonly blocks: readonly Block[] }>> = {
  'src/semantic.dark.tokens.json': {
    key: 'dark',
    blocks: [
      { media: '(prefers-color-scheme: dark)', selector: ":root:not([data-theme='light'])", colorScheme: 'dark' },
      { selector: "[data-theme='dark']", colorScheme: 'dark' },
    ],
  },
  'src/density.compact.tokens.json': { key: 'compact', blocks: [{ selector: "[data-density='compact']" }] },
  'src/motion.reduced.tokens.json': {
    key: 'reduced',
    blocks: [{ media: '(prefers-reduced-motion: reduce)', selector: ':root' }, { selector: "[data-motion='reduced']" }],
  },
};

type ModeKey = 'dark' | 'compact' | 'reduced';

interface Block {
  readonly media?: string;
  readonly selector: string;
  readonly colorScheme?: 'light' | 'dark';
}

interface EmittedToken extends ConvertedToken {
  readonly name: string;
  readonly type: TokenType;
  readonly file: string;
  readonly description: string | undefined;
}

const manifest = readManifest(packageRoot);
const resolved = new Map<string, readonly EmittedToken[]>();
for (const mode of modes(manifest)) resolved.set(mode.id, await resolveMode(mode));

const base = resolved.get('base') ?? [];
const lightFile = Object.entries(manifest.overrides).find(([, override]) => override.names === 'same')?.[1].base;

const cssBlocks = [
  declarations({ selector: ':root', colorScheme: 'light' }, base),
  declarations(
    { selector: "[data-theme='light']", colorScheme: 'light' },
    base.filter((token) => token.file === lightFile),
  ),
];
const modeValues = new Map<string, Partial<Record<ModeKey, EmittedToken>>>();
for (const [file] of Object.entries(manifest.overrides)) {
  const placement = placements[file];
  if (placement === undefined) throw new Error(`build: no CSS placement for the override ${file}`);
  const tokens = resolved.get(file) ?? [];
  for (const block of placement.blocks) cssBlocks.push(declarations(block, tokens));
  for (const token of tokens) modeValues.set(token.name, { ...modeValues.get(token.name), [placement.key]: token });
}

const header =
  'Avelune design tokens. Generated by @avelune/tokens (scripts/build.ts) from src/*.tokens.json; do not edit.';
const css = `/* ${header} */\n@layer tokens {\n${cssBlocks.join('\n\n')}\n}\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'tokens.css'), css);
writeFileSync(join(outDir, 'tokens.ts'), typescript(base, modeValues));
console.log(`build: wrote ${base.length} tokens to ${join(outDir, 'tokens.css')} and tokens.ts`);

async function resolveMode(mode: Mode): Promise<readonly EmittedToken[]> {
  const dictionary = new StyleDictionary({
    usesDtcg: true,
    source: mode.sources.map((file) => join(packageRoot, file)),
    log: { warnings: 'error', verbosity: 'verbose', errors: { brokenReferences: 'throw' } },
    platforms: { css: { transforms: [] } },
  });
  const { allTokens } = await dictionary.getPlatformTokens('css');
  const emitted = new Set(mode.emits.map((file) => join(packageRoot, file)));
  return allTokens
    .filter((token) => emitted.has(resolve(token.filePath)))
    .map((token) => {
      const type: unknown = token.$type;
      if (!isTokenType(type)) throw new Error(`build: ${token.path.join('.')} has unsupported type ${String(type)}`);
      const description: unknown = token.$description;
      const extensions: unknown = token['$extensions'];
      return {
        ...convertToken({ path: token.path, type, value: token.$value, extensions }),
        name: token.path.join('.'),
        type,
        file: relativeTo(packageRoot, token.filePath),
        description: typeof description === 'string' ? description : undefined,
      };
    });
}

function declarations(block: Block, tokens: readonly EmittedToken[]): string {
  const indent = block.media === undefined ? '  ' : '    ';
  const lines = [
    ...(block.colorScheme === undefined ? [] : [`color-scheme: ${block.colorScheme};`]),
    ...tokens.flatMap((token) => [
      `${token.cssVar}: ${token.css};`,
      ...Object.entries(token.parts).map(([name, value]) => `${name}: ${value};`),
    ]),
  ].map((line) => `${indent}  ${line}`);
  const rule = `${indent}${block.selector} {\n${lines.join('\n')}\n${indent}}`;
  return block.media === undefined ? rule : `  @media ${block.media} {\n${rule}\n  }`;
}

function typescript(
  tokens: readonly EmittedToken[],
  overrides: ReadonlyMap<string, Partial<Record<ModeKey, EmittedToken>>>,
) {
  const entries = tokens.map((token) => {
    const modesOf = overrides.get(token.name) ?? {};
    const fields = [
      `cssVar: ${JSON.stringify(token.cssVar)}`,
      `type: ${JSON.stringify(token.type)}`,
      `value: ${JSON.stringify(token.value)}`,
      `css: ${JSON.stringify(token.css)}`,
      ...(['dark', 'compact', 'reduced'] as const).flatMap((key) => {
        const mode = modesOf[key];
        return mode === undefined
          ? []
          : [`${key}: { value: ${JSON.stringify(mode.value)}, css: ${JSON.stringify(mode.css)} }`];
      }),
      ...(token.description === undefined ? [] : [`description: ${JSON.stringify(token.description)}`]),
    ];
    return `  ${JSON.stringify(token.name)}: {\n${fields.map((field) => `    ${field},`).join('\n')}\n  },`;
  });
  return `// ${header}

/** A token's value in one mode: the typed value and the CSS value of its custom property. */
export interface TokenModeValue {
  readonly value: unknown;
  readonly css: string;
}

export interface TokenDefinition extends TokenModeValue {
  /** The CSS custom property. */
  readonly cssVar: \`--ave-\${string}\`;
  /** The DTCG type. */
  readonly type: string;
  /** Value in the dark theme ([data-theme='dark'], or prefers-color-scheme: dark). Present on every themed token. */
  readonly dark?: TokenModeValue;
  /** Value under [data-density='compact']. Present only where compact density overrides the token. */
  readonly compact?: TokenModeValue;
  /** Value under prefers-reduced-motion: reduce and [data-motion='reduced']. Present only where it is overridden. */
  readonly reduced?: TokenModeValue;
  readonly description?: string;
}

/**
 * Every public token: the semantic and component tiers. Values are typed literals: colours as hex, dimensions in px,
 * durations in ms, easings as control points (the CSS value of the spring easing is linear()).
 */
export const tokens = {
${entries.join('\n')}
} as const satisfies Readonly<Record<string, TokenDefinition>>;

/** The name of every public token, as in the DTCG sources: \`color.bg.surface\`, \`space.4\`, \`duration.fast\`. */
export type TokenName = keyof typeof tokens;

/** A \`var()\` reference to a token, for inline styles and CSS-in-TS. */
export function tokenVar<N extends TokenName>(name: N): \`var(\${(typeof tokens)[N]['cssVar']})\` {
  return \`var(\${tokens[name].cssVar})\`;
}
`;
}

function relativeTo(root: string, file: string): string {
  const absolute = resolve(file);
  return absolute.startsWith(`${root}/`) ? absolute.slice(root.length + 1) : absolute;
}
