// Colour primitives from palette.config.ts (ADR 0011).
//
//   node scripts/generate-colors.ts            fail when src/primitives.color.tokens.json is not what the config
//                                              generates (CI; also catches hand edits)
//   node scripts/generate-colors.ts --update   regenerate the file (local, then review the diff)
//   node scripts/generate-colors.ts <file>     check another file instead (used by the tests)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { paletteConfig } from './palette.config.ts';
import { PaletteError, generatePalette, paletteToTokens, type Palette } from './palette.ts';

const packageRoot = join(import.meta.dirname, '..');
const committedFile = join(packageRoot, 'src', 'primitives.color.tokens.json');
const args = process.argv.slice(2);
const update = args.includes('--update');
const outputFile = resolve(args.find((arg) => !arg.startsWith('--')) ?? committedFile);

const description =
  'Colour primitives, generated by packages/tokens/scripts/generate-colors.ts from palette.config.ts. ' +
  'Do not edit: change the config and run `pnpm nx run tokens:colors --update` (ADR 0011).';

function generate(): Palette {
  try {
    return generatePalette(paletteConfig);
  } catch (error) {
    if (error instanceof PaletteError) {
      console.error(`colors: ${error.message}`);
      process.exit(1);
    }
    throw error;
  }
}

// Formatted with the repository's Prettier config, so the committed file passes `prettier --check` unchanged.
const prettierConfig = (await resolveConfig(committedFile)) ?? {};
const generated = await format(JSON.stringify(paletteToTokens(generate(), description)), {
  ...prettierConfig,
  filepath: committedFile,
});
const name = relative(process.cwd(), outputFile);

if (update) {
  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, generated);
  console.log(`colors: wrote ${name}`);
} else if (!existsSync(outputFile) || readFileSync(outputFile, 'utf8') !== generated) {
  console.error(
    `colors: ${name} is not what palette.config.ts generates. It was edited by hand or the config changed.\n` +
      'Run `pnpm nx run tokens:colors --update` and review the diff.',
  );
  process.exit(1);
} else {
  console.log(`colors: ${name} is up to date`);
}
