import type { AveBrandInput, AveBrandReport } from '@avelune/tokens/brand';
import { isAveBrandPreset } from '@avelune/tokens/brand/presets';

/** The `localStorage` key of the last brand applied on this device, with its stylesheet (ADR 0089). */
export const brandStorageKey = 'avelune:brand';

/** A brand as the kit keeps it: the input, the generator's fingerprint, its stylesheet and its report. */
export interface StoredBrand {
  /** The preset's name or the colour that was set. */
  readonly input: AveBrandInput;
  /** The fingerprint of the generator that wrote `css`: the stylesheet is kept while the kit generates it alike. */
  readonly fingerprint: string;
  /** The generated stylesheet. */
  readonly css: string;
  /** What the generator adapted. */
  readonly report: AveBrandReport;
}

/** Whether a value is a preset's name or a `#rrggbb` colour, the only brands the kit accepts (ADR 0089). */
export function isBrandInput(value: unknown): value is AveBrandInput {
  return typeof value === 'string' && (isAveBrandPreset(value) || /^#[0-9a-f]{6}$/i.test(value));
}

/** The lines a brand stylesheet may hold: the generator's own, colour declarations with computed hex values only. */
const stylesheetLines: readonly RegExp[] = [
  /^\/\* Avelune brand, generated by @avelune\/tokens\/brand \([0-9a-f]{12}\); do not edit\. \*\/$/,
  /^@layer tokens \{$/,
  /^ {2}(?::root|\[data-theme='light'\]|\[data-theme='dark'\]) \{$/,
  /^ {2}@media \(prefers-color-scheme: dark\) \{$/,
  /^ {4}:root:not\(\[data-theme='light'\]\) \{$/,
  /^ {4,6}--ave-[a-z0-9]+(?:-[a-z0-9]+)*: #[0-9a-f]{6}(?:[0-9a-f]{2})?;$/,
  /^ *\}$/,
  /^$/,
];

/**
 * Whether a stylesheet is one the brand generator writes: anything else (a stored value someone edited) is never
 * applied, so a brand can only ever change colour tokens to computed hex values.
 */
export function isBrandStylesheet(css: string): boolean {
  return css.split('\n').every((line) => stylesheetLines.some((pattern) => pattern.test(line)));
}

/** A stored brand, if it is well formed. */
export function parseStoredBrand(json: string | null): StoredBrand | undefined {
  if (json === null) return undefined;
  let value: unknown;
  try {
    value = JSON.parse(json);
  } catch {
    return undefined;
  }
  if (typeof value !== 'object' || value === null) return undefined;
  const input: unknown = Reflect.get(value, 'input');
  const fingerprint: unknown = Reflect.get(value, 'fingerprint');
  const css: unknown = Reflect.get(value, 'css');
  const report: unknown = Reflect.get(value, 'report');
  if (!isBrandInput(input) || typeof fingerprint !== 'string' || typeof css !== 'string') return undefined;
  if (typeof report !== 'object' || report === null || !isBrandStylesheet(css)) return undefined;
  return { input, fingerprint, css, report: report as AveBrandReport };
}

/**
 * The page's brand stylesheet: one constructed sheet adopted after the page's own, so its `@layer tokens` rules come
 * after `tokens.css` and win. A constructed sheet is not an inline style, so a strict `style-src` needs no nonce.
 */
export class BrandSheet {
  private sheet: CSSStyleSheet | undefined;

  constructor(private readonly document: Document) {}

  /** Paints a brand stylesheet, if it is one the generator writes, in place of the one before. */
  apply(css: string): void {
    const view = this.document.defaultView;
    if (view === null || !isBrandStylesheet(css)) return;
    this.sheet ??= new view.CSSStyleSheet();
    this.sheet.replaceSync(css);
    if (!this.document.adoptedStyleSheets.includes(this.sheet)) {
      this.document.adoptedStyleSheets = [...this.document.adoptedStyleSheets, this.sheet];
    }
  }

  /** Takes the brand stylesheet away: the kit's or the product's own colours show again. */
  remove(): void {
    const sheet = this.sheet;
    if (sheet === undefined) return;
    this.document.adoptedStyleSheets = this.document.adoptedStyleSheets.filter((adopted) => adopted !== sheet);
  }
}
