/** The id of the pre-paint script in `index.html`, by which `ng add` finds and replaces it (ADR 0103). */
export const prePaintId = 'avelune-pre-paint';

/**
 * The script's source, one statement per line for review; `ng add` writes it on one line.
 *
 * It applies the stored theme, density and motion as `AveTheme` does once the application runs: only the values the kit
 * knows, a preference that follows the system removing its attribute. It adopts the stored brand stylesheet when every
 * line is one the brand generator writes (the patterns of `isBrandStylesheet` in `@avelune/ui/theme`), without the
 * fingerprint, which changes with every kit version: `AveTheme` takes the sheet over at bootstrap and drops it when the
 * kit no longer generates it alike. Every storage access is guarded.
 */
const source = String.raw`
(() => {
  let storage = null;
  try { storage = window.localStorage; } catch {}
  const read = (key) => {
    try {
      const value = JSON.parse(storage?.getItem(key) ?? 'null');
      return typeof value === 'object' && value !== null ? value : {};
    } catch { return {}; }
  };
  const root = document.documentElement;
  const { theme, density, motion } = read('avelune:preferences');
  if (theme === 'light' || theme === 'dark') root.setAttribute('data-theme', theme);
  if (theme === 'system') root.removeAttribute('data-theme');
  if (density === 'compact') root.setAttribute('data-density', density);
  if (density === 'comfortable') root.removeAttribute('data-density');
  if (motion === 'reduced') root.setAttribute('data-motion', motion);
  if (motion === 'system') root.removeAttribute('data-motion');
  const { css } = read('avelune:brand');
  const lines = [
    /^\/\* Avelune brand, generated by @avelune\/tokens\/brand \([0-9a-f]{12}\); do not edit\. \*\/$/,
    /^@layer tokens \{$/,
    /^ {2}(?::root|\[data-theme='light'\]|\[data-theme='dark'\]) \{$/,
    /^ {2}@media \(prefers-color-scheme: dark\) \{$/,
    /^ {4}:root:not\(\[data-theme='light'\]\) \{$/,
    /^ {4,6}--ave-[a-z0-9]+(?:-[a-z0-9]+)*: #[0-9a-f]{6}(?:[0-9a-f]{2})?;$/,
    /^ *\}$/,
    /^$/,
  ];
  if (typeof css !== 'string' || css === '') return;
  if (!css.split('\n').every((line) => lines.some((pattern) => pattern.test(line)))) return;
  try {
    const sheet = new CSSStyleSheet();
    sheet.replaceSync(css);
    document.adoptedStyleSheets = [...document.adoptedStyleSheets, sheet];
  } catch {}
})();
`;

/**
 * The pre-paint script as `ng add` writes it into `index.html`: the source on one line, each line trimmed, so that an
 * HTML formatter has nothing to re-indent. Its text is a contract (ADR 0103): the schematics tests pin its hash, and a
 * change ships an `ng update` migration that replaces the block in every application.
 */
export const prePaintScript = source
  .split('\n')
  .map((line) => line.trim())
  .filter((line) => line !== '')
  .join(' ');
