// Generated by packages/tokens/scripts/generate-roles.ts with roles.ts. Do not edit (ADR 0089).

/**
 * The brand generator's fingerprint: a hash of its data and its code. A tenant's cached brand stylesheet is valid while
 * it holds, so a page applies the cache without loading the generator.
 */
export const aveBrandFingerprint = '771fdd313ef2';
